# Generated by Django 3.2.9 on 2022-12-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم الدولة بالعربي ')),
                ('name_en', models.CharField(max_length=50, verbose_name='اسم الدولة بالنجلزي ')),
                ('key_country', models.IntegerField(verbose_name='مفتاح الدولة ')),
                ('status', models.IntegerField(choices=[(1, 'PEINGIN'), (2, 'ACTIVTE'), (3, 'DEACTIVTE')], default=2)),
            ],
            options={
                'verbose_name': 'البلد',
                'verbose_name_plural': 'البلدان',
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم المنطقةبالعربي')),
                ('name_en', models.CharField(max_length=50, verbose_name='اسم المنطقة بالانجلزي')),
                ('coed', models.IntegerField(verbose_name='مفتاح المنظقة ')),
                ('status', models.IntegerField(choices=[(1, 'PEINGIN'), (2, 'ACTIVTE'), (3, 'DEACTIVTE')], default=2)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.country', verbose_name='البلد')),
            ],
            options={
                'verbose_name': 'المنظقة ',
                'verbose_name_plural': 'المناطق ',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=50, verbose_name='اسم  المدينة بالعربي ')),
                ('name_en', models.CharField(max_length=50, verbose_name='اسم المدينة بالانجلزي ')),
                ('status', models.IntegerField(choices=[(1, 'PEINGIN'), (2, 'ACTIVTE'), (3, 'DEACTIVTE')], default=2)),
                ('governorate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='place.governorate', verbose_name='المناطق')),
            ],
            options={
                'verbose_name': 'المدينة',
                'verbose_name_plural': 'المدن',
            },
        ),
    ]
