# Generated by Django 3.2.9 on 2023-01-26 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='place.governorate', verbose_name='المناطق'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governors', to='place.country', verbose_name='البلد'),
        ),
    ]
