# Generated by Django 3.2.9 on 2024-02-20 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20230126_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'country', 'verbose_name_plural': 'countries'},
        ),
        migrations.AlterModelOptions(
            name='governorate',
            options={'verbose_name': 'governorate', 'verbose_name_plural': 'governors'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='city',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='city',
            name='status',
        ),
        migrations.RemoveField(
            model_name='country',
            name='key_country',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='country',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='country',
            name='status',
        ),
        migrations.RemoveField(
            model_name='governorate',
            name='coed',
        ),
        migrations.RemoveField(
            model_name='governorate',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='governorate',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='governorate',
            name='status',
        ),
        migrations.AddField(
            model_name='city',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='country name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='governorate',
            name='name',
            field=models.CharField(default=None, max_length=50, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='place.governorate', verbose_name='governorate'),
        ),
        migrations.AlterField(
            model_name='governorate',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='governors', to='place.country', verbose_name='country'),
        ),
    ]
