# Generated by Django 3.2.9 on 2024-02-20 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_at', models.DateTimeField(auto_now_add=True, verbose_name='add at')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('notes', models.TextField(verbose_name='notes')),
                ('dont_call', models.BooleanField(verbose_name='dont call')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='ClientGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_at', models.DateTimeField(auto_now_add=True, verbose_name='add at')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
            options={
                'verbose_name': 'ClientsGroup',
                'verbose_name_plural': 'ClientsGroups',
            },
        ),
        migrations.CreateModel(
            name='ClientContactData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(max_length=50, verbose_name='type')),
                ('data', models.CharField(max_length=1024, verbose_name='data')),
                ('active', models.BooleanField(verbose_name='active')),
                ('note', models.TextField(verbose_name='note')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_data', to='lead.client')),
            ],
            options={
                'verbose_name': 'ClientContactData',
                'verbose_name_plural': 'ClientContactDatas',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='groups',
            field=models.ManyToManyField(related_name='clients', to='lead.ClientGroup'),
        ),
    ]
