# Generated by Django 3.2.9 on 2024-02-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientcontactdata',
            options={'verbose_name': 'ClientContactData', 'verbose_name_plural': 'Client Contact Data'},
        ),
        migrations.AlterModelOptions(
            name='clientgroup',
            options={'verbose_name': 'Clients Group', 'verbose_name_plural': 'Clients Groups'},
        ),
        migrations.AlterField(
            model_name='client',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='clientcontactdata',
            name='contact_type',
            field=models.CharField(choices=[('twitter', 'twitter'), ('phone', 'phone'), ('email', 'email')], max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='clientcontactdata',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
    ]
