# Generated by Django 5.0.2 on 2024-02-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0002_auto_20240220_0111"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientcontactdata",
            options={
                "verbose_name": "client contact data",
                "verbose_name_plural": "Client Contact Data",
            },
        ),
        migrations.AlterField(
            model_name="clientcontactdata",
            name="contact_type",
            field=models.CharField(
                choices=[
                    ("twitter", "Twitter"),
                    ("facebook", "Facebook"),
                    ("linkedin", "LinkedIn"),
                    ("instagram", "Instagram"),
                    ("email", "Email"),
                    ("phone", "Phone"),
                    ("other", "Other"),
                ],
                max_length=50,
                verbose_name="type",
            ),
        ),
    ]
