# Generated by Django 3.2.9 on 2024-02-20 01:31

import department.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('place', '0003_auto_20240220_0111'),
        ('lead', '0002_auto_20240220_0111'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='attr/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'متغير',
                'verbose_name_plural': 'المتغيرات',
            },
        ),
        migrations.CreateModel(
            name='AttributeChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_ar', models.CharField(max_length=100, verbose_name=' الاختيار بالعربيه')),
                ('choice_en', models.CharField(max_length=100, verbose_name=' الاختيار بالانجليزيه')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='attr/', verbose_name='logo')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='department.attribute', verbose_name='المتفير')),
            ],
            options={
                'verbose_name': 'خيار',
                'verbose_name_plural': 'خيارات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('status', models.IntegerField(choices=[(1, 'PEINGIN'), (2, 'ACTIVTE'), (3, 'DEACTIVTE')], default=2, verbose_name='status')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='logo')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'التصنيف',
                'verbose_name_plural': 'التصانيف',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='title')),
                ('decr', models.TextField(blank=True, null=True, verbose_name='description')),
                ('status', models.IntegerField(choices=[(1, 'PEINGIN'), (2, 'ACTIVTE'), (3, 'DEACTIVTE')], default=2, verbose_name='status')),
                ('status_item', models.IntegerField(choices=[(1, 'NEW'), (2, 'USED'), (3, 'OLD')], default=2, verbose_name='property status')),
                ('video', models.FileField(blank=True, null=True, upload_to='video', verbose_name='video')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=20)),
                ('date', models.DateField(auto_now_add=True, null=True, verbose_name='add at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='department.category', verbose_name='القسم')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='place.city', verbose_name='المدينة')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lead.client')),
            ],
            options={
                'verbose_name': 'المنتجات',
                'verbose_name_plural': 'المنتجات',
            },
            managers=[
                ('objects', department.managers.PropertyManager()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='item_type/', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'نوع المنتج',
                'verbose_name_plural': 'نوع المنتجات',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم الصورة')),
                ('pic', models.ImageField(upload_to=None, verbose_name='الصورة')),
                ('text', tinymce.models.HTMLField(blank=True, verbose_name='وصف في الصورة')),
            ],
            options={
                'verbose_name': 'الخلفية',
                'verbose_name_plural': 'الخلفيات',
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media', verbose_name='pic')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='department.property', verbose_name='صور المنتج')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='department.attributechoice', verbose_name='القيمه')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='department.property', verbose_name='القيم')),
            ],
            options={
                'verbose_name': 'قيمة المتغيرات',
                'verbose_name_plural': 'قيم المتغيرات',
            },
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='department.propertytype', verbose_name='نوع المنتج'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='department.propertytype', verbose_name='نوع المتغير '),
        ),
    ]
