# Generated by Django 3.2.9 on 2024-02-20 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'verbose_name': 'attribute', 'verbose_name_plural': 'attributes'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'property', 'verbose_name_plural': 'properties'},
        ),
        migrations.AlterModelOptions(
            name='propertytype',
            options={'verbose_name': 'property type', 'verbose_name_plural': 'property types'},
        ),
        migrations.RenameField(
            model_name='attributechoice',
            old_name='choice_ar',
            new_name='choice',
        ),
        migrations.RemoveField(
            model_name='attributechoice',
            name='choice_en',
        ),
        migrations.AlterField(
            model_name='attribute',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='department.propertytype', verbose_name='attributes'),
        ),
        migrations.AlterField(
            model_name='attributechoice',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='department.attribute', verbose_name='attribute'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='department.propertytype', verbose_name='property type'),
        ),
        migrations.AlterField(
            model_name='propertyattributevalue',
            name='choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='department.attributechoice', verbose_name='value'),
        ),
        migrations.AlterField(
            model_name='propertyattributevalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attr_values', to='department.property', verbose_name='values'),
        ),
    ]
