# Generated by Django 3.2.9 on 2024-02-20 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20240220_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='users',
        ),
    ]
