# Generated by Django 3.2.9 on 2024-02-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_remove_category_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='want',
            field=models.CharField(choices=[('sell', 'sell'), ('rent', 'rent'), ('change', 'change')], default='sell', max_length=50, verbose_name='want to'),
            preserve_default=False,
        ),
    ]
