# Generated by Django 5.0.2 on 2024-03-28 15:45

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0006_alter_category_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attributechoice",
            options={"verbose_name": "choice", "verbose_name_plural": "options"},
        ),
        migrations.AlterModelOptions(
            name="propertyattributevalue",
            options={
                "verbose_name": "attribute value",
                "verbose_name_plural": "attribute values",
            },
        ),
        migrations.AddField(
            model_name="property",
            name="price_currency",
            field=djmoney.models.fields.CurrencyField(
                choices=[("EUR", "EUR €"), ("USD", "USD $")],
                default="USD",
                editable=False,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="attributechoice",
            name="choice",
            field=models.CharField(max_length=100, verbose_name=" choice "),
        ),
        migrations.AlterField(
            model_name="property",
            name="price",
            field=djmoney.models.fields.MoneyField(
                decimal_places=2,
                default=Decimal("0.0"),
                default_currency="USD",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="propertyimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="department.property",
                verbose_name="property image",
            ),
        ),
    ]
