# Generated by Django 3.2.9 on 2024-02-20 03:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0005_property_want'),
        ('lead', '0002_auto_20240220_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('on progress', 'on progress'), ('done', 'done'), ('fail', 'fail')], max_length=50, verbose_name='status')),
                ('price', models.IntegerField(verbose_name='price')),
                ('description', models.TextField(verbose_name='description')),
                ('commotion', models.IntegerField(verbose_name='commotion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('clients', models.ManyToManyField(to='lead.Client')),
                ('deal_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='department.property', verbose_name='property')),
            ],
            options={
                'verbose_name': 'Deal',
                'verbose_name_plural': 'Deals',
            },
        ),
        migrations.CreateModel(
            name='SalesManProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('total_commotions', models.IntegerField(verbose_name='total amount of commotions')),
                ('total_paid_commotions', models.IntegerField(verbose_name='total paid amount of commotions')),
                ('active', models.BooleanField(verbose_name='active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sales_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SalesManCommotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('paid', models.BooleanField(default=False, verbose_name='paid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('last_update', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_man_commotion', to='sales.deal', verbose_name='deal')),
                ('sales_man', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commotions', to='sales.salesmanprofile', verbose_name='sales_man')),
            ],
            options={
                'verbose_name': 'Sales Man Commotion',
                'verbose_name_plural': 'Sales Man Commotions',
            },
        ),
    ]
