# Generated by Django 5.0.2 on 2024-02-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0003_alter_clientcontactdata_options_and_more"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deal",
            name="clients",
            field=models.ManyToManyField(
                related_name="deals", to="lead.client", verbose_name="clients"
            ),
        ),
        migrations.AlterField(
            model_name="salesmanprofile",
            name="active",
            field=models.BooleanField(default=True, verbose_name="active"),
        ),
        migrations.AlterField(
            model_name="salesmanprofile",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created at"),
        ),
        migrations.AlterField(
            model_name="salesmanprofile",
            name="total_commotions",
            field=models.IntegerField(
                default=0, verbose_name="total amount of commotions"
            ),
        ),
        migrations.AlterField(
            model_name="salesmanprofile",
            name="total_paid_commotions",
            field=models.IntegerField(
                default=0, verbose_name="total paid amount of commotions"
            ),
        ),
    ]
