# Generated by Django 5.0.2 on 2024-03-28 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0007_alter_attributechoice_options_and_more"),
        ("lead", "0003_alter_clientcontactdata_options_and_more"),
        ("sales", "0002_alter_deal_clients_alter_salesmanprofile_active_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PropertyRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_from",
                    models.PositiveIntegerField(verbose_name="budget start from"),
                ),
                (
                    "budget_to",
                    models.PositiveIntegerField(verbose_name="budget end to"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="lead.client",
                        verbose_name="properties requests",
                    ),
                ),
                (
                    "property_types",
                    models.ManyToManyField(
                        related_name="request", to="department.propertytype"
                    ),
                ),
            ],
            options={
                "verbose_name": "Property Request",
                "verbose_name_plural": "Property Requests",
            },
        ),
        migrations.CreateModel(
            name="PropertyRequestsAttributeValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_request_values",
                        to="department.attributechoice",
                        verbose_name="value",
                    ),
                ),
                (
                    "property_requests",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="request_attr_values",
                        to="department.property",
                        verbose_name="values",
                    ),
                ),
            ],
            options={
                "verbose_name": "PropertyRequestsAttributeValue",
                "verbose_name_plural": "PropertyRequestsAttributeValues",
            },
        ),
    ]
